branch-defaults:
  master:
    environment: <environment-name>
    group_suffix: null
global:
  application_name: <application-name>
  branch: null
  default_ec2_keyname: <ec2-ssl-cert-name>
  default_platform: Ruby 2.3 (Puma)
  default_region: <region>
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: <aws-eb-cli-profile>
  repository: null
  sc: git
  workspace_type: Application
